Repository IBM/cloudpak-gitops, pull requests merged in 2024-05, with the labels that each got.

#328 feat: Upgrade Cloud Pak for AIOps to 4.4.0
  .github/workflows/close-pr.yml
  .github/workflows/lint.yml
  .github/workflows/test-pr.yml
  README.md
  config/cloudpaks/cp-shared/operators/Chart.yaml
  config/cloudpaks/cp-shared/operators/templates/0050-sync-cluster-scoped-operators.yaml
  config/cloudpaks/cp-shared/operators/values.yaml
  config/cloudpaks/cp4aiops/install-aimgr/Chart.yaml
  config/cloudpaks/cp4aiops/install-aimgr/templates/resources/200-ai-manager.yaml
  config/cloudpaks/cp4aiops/install-aimgr/templates/subscriptions/100-subscription.yaml
  config/cloudpaks/cp4aiops/install-aimgr/values.yaml
  config/cloudpaks/cp4aiops/install-ia/Chart.yaml
  config/cloudpaks/cp4aiops/install-ia/templates/subscriptions/100-subscription.yaml
  tests/postbuild/cluster.sh
Labels: enhancement, chore

#333 Update rhacm.md add --helm-set repoURL on argoCD-control-plane create
  docs/rhacm.md
Labels: bug

#335 fix: Update CP4I 2023.4.1 versions
  config/cloudpaks/cp-shared/operators/templates/0050-catalog-source-foundation-services.yaml
  config/cloudpaks/cp4i/install-mq/Chart.yaml
  config/cloudpaks/cp4i/install-mq/templates/0050-catalog-source-mq.yaml
  config/cloudpaks/cp4i/install-mq/templates/0100-subscription-mq.yaml
  config/cloudpaks/cp4i/install-mq/templates/0210-queue-manager.yaml
  config/cloudpaks/cp4i/install-platform/Chart.yaml
  config/cloudpaks/cp4i/install-platform/templates/0050-catalog-source-platform-navigator.yaml
  config/cloudpaks/cp4i/install-prereqs/Chart.yaml
  config/cloudpaks/cp4i/install-prereqs/values.yaml
Labels: chore

#232 feat: Make ArgoCD use cluster cert
  config/argocd/Chart.yaml
  config/argocd/templates/0200-argocd.yaml
  tests/postbuild/gitops.sh
Labels: enhancement
